'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { LogOut, Share2, ShieldAlert, Sparkles, UserRound, Wand2 } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { generateMirrorCard, generateResonanceText, scorePulseMatch, type MirrorCard, type Pulse, type PulseDraft, type Resonance } from '@mirror/core';
import { blockUser, completeOnboarding, createMirrorCard, createPulse, createReport, createResonance, deletePulse, findCandidatePulses, getPulse, getResonance, listUserMirrorCards, listUserPulses, listUserResonances, logout, makePulsePrivate, signInAnonymous, signInWithGoogle } from '@mirror/firebase';
import { PulseForm } from './PulseForm';
import { MirrorCardView } from './MirrorCardView';
import { useFirebaseUser } from '../hooks/useFirebaseUser';
import type { MirrorView } from '../lib/routes';
type Status = { kind: 'idle'|'loading'|'error'|'done'; message: string };
export function MirrorAppShell({ view, id }: { view: MirrorView; id?: string }) { const router = useRouter(); const { user, loading, configured } = useFirebaseUser(); const [status, setStatus] = useState<Status>({ kind:'idle', message:'' }); const [pulses, setPulses] = useState<Pulse[]>([]); const [resonances, setResonances] = useState<Resonance[]>([]); const [cards, setCards] = useState<MirrorCard[]>([]); const [selectedPulse, setSelectedPulse] = useState<Pulse | null>(null); const [selectedResonance, setSelectedResonance] = useState<Resonance | null>(null); const latestCard = cards[0];
  const refresh = useCallback(async (uid: string) => { try { const [ps, rs, cs] = await Promise.all([listUserPulses(uid), listUserResonances(uid), listUserMirrorCards(uid)]); setPulses(ps); setResonances(rs); setCards(cs); } catch (e) { setStatus({ kind:'error', message:e instanceof Error ? e.message : '読み込みに失敗しました' }); } }, []);
  useEffect(() => { if (!user) return; void refresh(user.uid); }, [user, refresh]);
  useEffect(() => { if (!id) return; if (view === 'pulse-detail') getPulse(id).then(setSelectedPulse).catch((e) => setStatus({ kind:'error', message:e.message })); if (view === 'resonance-detail') getResonance(id).then(setSelectedResonance).catch((e) => setStatus({ kind:'error', message:e.message })); }, [id, view]);
  async function ensureUser() { if (user) return user; setStatus({ kind:'loading', message:'匿名の鏡を作っています...' }); return await signInAnonymous(); }
  async function submitPulse(draft: PulseDraft) { try { const current = await ensureUser(); const pulse = await createPulse(current.uid, draft); const candidates = await findCandidatePulses(pulse, 40); const scored = candidates.map((candidate) => ({ pulse: candidate, result: scorePulseMatch(pulse, candidate, []) })).filter((item) => item.result.matched).sort((a,b) => b.result.score - a.result.score).slice(0, 20); const text = generateResonanceText({ color: pulse.color, mood: pulse.mood, count: scored.length, strongCount: scored.filter((s) => s.result.strong).length }); const resonance = await createResonance({ pulseId: pulse.id, uid: current.uid, dateKey: pulse.dateKey, matchedPulseIds: scored.slice(0, 20).map((s) => s.pulse.id), matchCount: scored.length, dominantMatchTypes: Array.from(new Set(scored.flatMap((s) => s.result.matchTypes))).slice(0, 5), score: scored[0]?.result.score || 0, title: text.title, body: text.body }); const draftCard = generateMirrorCard({ uid: current.uid, pulseId: pulse.id, resonanceId: resonance.id, dateKey: pulse.dateKey, color: pulse.color, mood: pulse.mood, matchCount: scored.length }); const card = await createMirrorCard({ uid: draftCard.uid, pulseId: draftCard.pulseId, resonanceId: draftCard.resonanceId, dateKey: draftCard.dateKey, title: draftCard.title, copy: draftCard.copy, color: draftCard.color, gradient: draftCard.gradient, statsText: draftCard.statsText }); await completeOnboarding(current.uid); setPulses((prev) => [pulse, ...prev]); setResonances((prev) => [resonance, ...prev]); setCards((prev) => [card, ...prev]); setStatus({ kind:'done', message:'今日の断片が世界に同期しました。' }); router.push('/mirror'); } catch (e) { setStatus({ kind:'error', message:e instanceof Error ? e.message : 'Pulseを保存できませんでした' }); } }
  async function shareCard(card: MirrorCard) { const text = card.statsText + ' #MIRROR'; if (navigator.share) await navigator.share({ title: 'MIRROR', text }); else await navigator.clipboard.writeText(text); setStatus({ kind:'done', message:'共有コピーを用意しました。' }); }
  const cityMood = useMemo(() => { const today = pulses[0]?.dateKey; const todayPulses = pulses.filter((p) => p.dateKey === today); return { count: todayPulses.length, color: todayPulses[0]?.color || 'Blue', mood: todayPulses[0]?.mood || '静けさ' }; }, [pulses]);
  const nav = <nav className="mx-auto flex w-full max-w-5xl items-center justify-between px-4 py-5"><Link href="/" className="text-lg font-semibold tracking-[.24em]">MIRROR</Link><div className="flex items-center gap-2 text-sm text-white/70"><Link href="/home">Home</Link><Link href="/me">Log</Link><Link href="/settings">Settings</Link></div></nav>;
  return <main className="relative min-h-screen">{nav}<div className="mx-auto w-full max-w-5xl px-4 pb-16">{status.message && <div className={'mb-4 rounded-lg border px-4 py-3 text-sm ' + (status.kind === 'error' ? 'border-red-300/25 bg-red-500/10 text-red-100' : 'border-white/14 bg-white/8 text-white/78')}>{status.message}</div>}{!configured && <SetupNotice />}{loading && <EmptyState title="鏡面を起こしています" body="ほんの少しだけ、夜の焦点を合わせています。" />}{view === 'landing' && <Landing onStart={() => router.push('/start')} />}{view === 'start' && <Start onSubmit={submitPulse} />}{view === 'mirror' && <Mirror latestCard={latestCard} latestResonance={resonances[0]} onShare={shareCard} onGoogle={signInWithGoogle} userAnonymous={Boolean(user?.isAnonymous)} />}{view === 'home' && <Home userReady={Boolean(user)} pulses={pulses} resonances={resonances} latestCard={latestCard} cityMood={cityMood} onSubmit={submitPulse} />}{view === 'pulse-new' && <Start onSubmit={submitPulse} title="今日のPulse" />}{view === 'pulse-detail' && <PulseDetail pulse={selectedPulse} onPrivate={async () => selectedPulse && makePulsePrivate(selectedPulse.id).then(() => router.push('/me'))} onDelete={async () => selectedPulse && deletePulse(selectedPulse.id).then(() => router.push('/me'))} />}{view === 'resonance-detail' && <ResonanceDetail resonance={selectedResonance} />}{view === 'city' && <City pulses={pulses} cityMood={cityMood} />}{view === 'me' && <Me pulses={pulses} cards={cards} resonances={resonances} />}{view === 'settings' && <Settings onGoogle={signInWithGoogle} onLogout={logout} onBlock={async (target) => { if (!user) return; await blockUser(user.uid, target); }} isAnonymous={Boolean(user?.isAnonymous)} />}{view === 'report' && <ReportForm userId={user?.uid} onReport={async (targetType, targetId, reason, details) => { const current = user || await ensureUser(); await createReport({ reporterUid: current.uid, targetType, targetId, reason, details }); setStatus({ kind:'done', message:'通報を受け取りました。MIRRORの静けさを守ります。' }); }} />}</div></main>;
}
function SetupNotice() { return <div className="mb-6 rounded-lg border border-amber-200/20 bg-amber-300/10 p-4 text-sm text-amber-50">Firebase 環境変数が未設定です。画面確認はできますが、匿名ログインと Firestore 保存には .env.local が必要です。</div>; }
function Landing({ onStart }: { onStart: () => void }) { return <section className="grid min-h-[78vh] items-center gap-8 py-8 lg:grid-cols-[1fr_.8fr]"><div><p className="text-sm tracking-[.28em] text-blue-100/70">WORLD SYNC SNS</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold tracking-normal text-white sm:text-7xl">MIRROR</h1><p className="mt-5 max-w-xl text-xl leading-9 text-white/78">世界のどこかに、今日のあなたと似た人がいる。</p><p className="mt-8 max-w-2xl text-base leading-8 text-white/62">色を選ぶ。気分を選ぶ。今日、目に残ったものを一言だけ残す。それだけで、同じ夜に似た静けさを抱えていた誰かと匿名で響き合う。</p><button onClick={onStart} className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-lg bg-white px-5 py-3 font-medium text-slate-950"><Wand2 size={18}/>今日のPulseを残す</button></div><div className="rounded-lg border border-white/14 bg-white/[.07] p-5 backdrop-blur-xl"><div className="rounded-lg bg-[linear-gradient(135deg,#07142d,#5c3bb9_58%,#ffd4e5)] p-6 shadow-2xl"><p className="text-xs tracking-[.3em] text-white/70">TONIGHT</p><p className="mt-28 text-2xl leading-9">今夜、あなたと同じ青を選んだ人がいる。</p></div></div></section>; }
function Start({ onSubmit, title = 'First Pulse' }: { onSubmit: (draft: PulseDraft) => Promise<void>; title?: string }) { return <section className="mx-auto max-w-2xl py-8"><p className="text-sm tracking-[.24em] text-blue-100/70">30 SECONDS</p><h1 className="mt-4 text-4xl font-semibold">{title}</h1><p className="mt-3 text-white/62">登録フォームはあとでいい。まず、今日の断片をひとつだけ。</p><div className="mt-8 rounded-lg border border-white/14 bg-white/[.07] p-5 backdrop-blur-xl"><PulseForm onSubmit={onSubmit} /></div></section>; }
function Mirror({ latestCard, latestResonance, onShare, onGoogle, userAnonymous }: { latestCard?: MirrorCard; latestResonance?: Resonance; onShare: (card: MirrorCard) => void; onGoogle: () => void; userAnonymous: boolean }) { return <section className="grid gap-8 py-8 lg:grid-cols-[.8fr_1fr]"><div>{latestCard ? <MirrorCardView card={latestCard}/> : <EmptyState title="まだ反射は遠くにある" body="Pulseを残すと、ここに今日のMirror Cardが現れます。" />}</div><div className="self-center"><p className="text-sm tracking-[.24em] text-pink-100/70">RESONANCE</p><h1 className="mt-4 text-4xl font-semibold">{latestResonance?.title || '今日のあなたは、ひとりではなかった。'}</h1><p className="mt-5 leading-8 text-white/68">{latestResonance?.body || 'データが少ない夜でも、あなたのPulseは記録されます。世界側の断片が増えたとき、反射は濃くなっていきます。'}</p><div className="mt-8 flex flex-wrap gap-3">{latestCard && <button onClick={() => onShare(latestCard)} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-white px-4 text-sm font-medium text-slate-950"><Share2 size={16}/>共有</button>}{userAnonymous && <button onClick={onGoogle} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-white/15 px-4 text-sm text-white"><UserRound size={16}/>Googleで保存継続</button>}<Link href="/home" className="inline-flex min-h-11 items-center rounded-lg border border-white/15 px-4 text-sm text-white">Homeへ</Link></div></div></section>; }
function Home({ userReady, pulses, resonances, latestCard, cityMood, onSubmit }: { userReady: boolean; pulses: Pulse[]; resonances: Resonance[]; latestCard?: MirrorCard; cityMood: { count:number; color:string; mood:string }; onSubmit: (draft: PulseDraft) => Promise<void> }) { return <section className="grid gap-6 py-6 lg:grid-cols-[1fr_.8fr]"><div><h1 className="text-3xl font-semibold">今日、何を残す？</h1><p className="mt-2 text-white/62">{userReady ? '今日のPulseと最近の響き。必要なものだけをここに。' : '匿名で始められます。'}</p><div className="mt-6 rounded-lg border border-white/14 bg-white/[.07] p-5"><PulseForm onSubmit={onSubmit} compact /></div><div className="mt-6 rounded-lg border border-white/14 bg-white/[.07] p-5"><h2 className="font-medium">最近の記録</h2>{pulses.length === 0 ? <p className="mt-3 text-sm text-white/55">まだPulseはありません。</p> : <div className="mt-3 space-y-2">{pulses.slice(0,5).map((p) => <Link key={p.id} href={'/pulse/' + p.id} className="block rounded-lg border border-white/10 px-3 py-2 text-sm text-white/75">{p.dateKey} / {p.color} / {p.mood} / {p.word}</Link>)}</div>}</div></div><div className="space-y-6">{latestCard && <MirrorCardView card={latestCard}/>}<div className="rounded-lg border border-white/14 bg-white/[.07] p-5"><h2 className="font-medium">City Mood</h2><p className="mt-4 text-2xl">{cityMood.color} / {cityMood.mood}</p><p className="mt-2 text-sm text-white/58">正確な位置情報は保存しません。cityBucket は任意です。</p><Link href="/city" className="mt-4 inline-flex text-sm text-blue-100">Cityを見る</Link></div><div className="rounded-lg border border-white/14 bg-white/[.07] p-5"><h2 className="font-medium">Resonance</h2><p className="mt-3 text-sm text-white/62">{resonances[0]?.title || '今日の響きはまだ薄いままです。'}</p></div></div></section>; }
function PulseDetail({ pulse, onPrivate, onDelete }: { pulse: Pulse | null; onPrivate: () => void; onDelete: () => void }) { if (!pulse) return <EmptyState title="Pulseを探しています" body="見つからない場合、本人だけが読めるPulseかもしれません。" />; return <section className="mx-auto max-w-2xl py-8"><h1 className="text-3xl font-semibold">{pulse.color} / {pulse.mood}</h1><p className="mt-5 rounded-lg border border-white/14 bg-white/[.07] p-5 text-xl leading-9">{pulse.word}</p><div className="mt-5 flex gap-3"><button onClick={onPrivate} className="rounded-lg border border-white/15 px-4 py-2 text-sm">非公開化</button><button onClick={onDelete} className="rounded-lg border border-red-200/25 px-4 py-2 text-sm text-red-100">削除</button><Link href={'/report?targetType=pulse&targetId=' + pulse.id} className="rounded-lg border border-white/15 px-4 py-2 text-sm">通報導線</Link></div></section>; }
function ResonanceDetail({ resonance }: { resonance: Resonance | null }) { return <section className="mx-auto max-w-2xl py-8"><Sparkles/><h1 className="mt-4 text-3xl font-semibold">{resonance?.title || 'Resonance'}</h1><p className="mt-5 leading-8 text-white/68">{resonance?.body || '響きの詳細を読み込んでいます。'}</p></section>; }
function City({ pulses, cityMood }: { pulses: Pulse[]; cityMood: { count:number; color:string; mood:string } }) { return <section className="py-8"><h1 className="text-3xl font-semibold">City Mood</h1><p className="mt-3 text-white/62">街は任意の粗い bucket のみ。正確な位置情報は扱いません。</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-white/14 bg-white/[.07] p-5"><p className="text-sm text-white/50">Dominant</p><p className="mt-3 text-2xl">{cityMood.color}</p></div><div className="rounded-lg border border-white/14 bg-white/[.07] p-5"><p className="text-sm text-white/50">Mood</p><p className="mt-3 text-2xl">{cityMood.mood}</p></div><div className="rounded-lg border border-white/14 bg-white/[.07] p-5"><p className="text-sm text-white/50">Your Pulses</p><p className="mt-3 text-2xl">{pulses.length}</p></div></div></section>; }
function Me({ pulses, cards, resonances }: { pulses: Pulse[]; cards: MirrorCard[]; resonances: Resonance[] }) { return <section className="py-8"><h1 className="text-3xl font-semibold">Mirror Log</h1><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Pulses" value={pulses.length}/><Metric label="Cards" value={cards.length}/><Metric label="Resonances" value={resonances.length}/></div><div className="mt-8 grid gap-4 lg:grid-cols-2">{cards.slice(0,2).map((c) => <MirrorCardView key={c.id} card={c}/>)}{pulses.map((p) => <Link key={p.id} href={'/pulse/' + p.id} className="rounded-lg border border-white/14 bg-white/[.07] p-4"><p className="text-sm text-white/50">{p.dateKey}</p><p className="mt-2">{p.word}</p></Link>)}</div></section>; }
function Metric({ label, value }: { label:string; value:number }) { return <div className="rounded-lg border border-white/14 bg-white/[.07] p-5"><p className="text-sm text-white/50">{label}</p><p className="mt-2 text-3xl">{value}</p></div>; }
function Settings({ onGoogle, onLogout, onBlock, isAnonymous }: { onGoogle: () => void; onLogout: () => void; onBlock: (target:string) => Promise<void>; isAnonymous:boolean }) { const [target, setTarget] = useState(''); return <section className="mx-auto max-w-2xl py-8"><h1 className="text-3xl font-semibold">Settings</h1><div className="mt-6 space-y-4 rounded-lg border border-white/14 bg-white/[.07] p-5"><p className="text-white/62">本名、顔写真、正確な位置情報は不要です。Google連携は保存継続のためだけに使います。</p>{isAnonymous && <button onClick={onGoogle} className="min-h-11 rounded-lg bg-white px-4 text-sm text-slate-950">Googleで保存継続</button>}<div><label className="text-sm text-white/70">ブロックする uid<input className="field mt-2" value={target} onChange={(e) => setTarget(e.target.value)} /></label><button onClick={() => target && onBlock(target)} className="mt-3 rounded-lg border border-white/15 px-4 py-2 text-sm">ブロック</button></div><button onClick={onLogout} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-white/15 px-4 text-sm"><LogOut size={16}/>ログアウト</button></div></section>; }
function ReportForm({ userId, onReport }: { userId?: string; onReport: (targetType:'pulse'|'user'|'resonance', targetId:string, reason:string, details?:string) => Promise<void> }) { const [targetType, setTargetType] = useState<'pulse'|'user'|'resonance'>('pulse'); const [targetId, setTargetId] = useState(''); const [reason, setReason] = useState('harassment'); const [details, setDetails] = useState(''); return <section className="mx-auto max-w-2xl py-8"><ShieldAlert/><h1 className="mt-4 text-3xl font-semibold">通報</h1><p className="mt-3 text-white/62">コメントもDMもない設計ですが、公開Pulseやユーザーの問題はここから送れます。</p><div className="mt-6 space-y-4 rounded-lg border border-white/14 bg-white/[.07] p-5"><select className="field" value={targetType} onChange={(e) => setTargetType(e.target.value as 'pulse'|'user'|'resonance')}><option value="pulse">pulse</option><option value="user">user</option><option value="resonance">resonance</option></select><input className="field" value={targetId} onChange={(e) => setTargetId(e.target.value)} placeholder="target id"/><input className="field" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="reason"/><textarea className="field min-h-28" value={details} onChange={(e) => setDetails(e.target.value)} placeholder="details"/><button disabled={!userId && !targetId} onClick={() => onReport(targetType, targetId, reason, details)} className="min-h-11 rounded-lg bg-white px-4 text-sm text-slate-950 disabled:opacity-40">送信</button></div></section>; }
function EmptyState({ title, body }: { title:string; body:string }) { return <div className="rounded-lg border border-white/14 bg-white/[.07] p-8 text-center"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-white/58">{body}</p></div>; }
