import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, updateDoc, where } from 'firebase/firestore';
import { createPulseData, type Pulse, type PulseDraft } from '@mirror/core';
import { getFirebaseClients } from '../client';
import { incrementUserStats } from './users';
export async function createPulse(uid: string, draft: PulseDraft): Promise<Pulse> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); const data = createPulseData(uid, draft); const ref = await addDoc(collection(clients.db, 'pulses'), { ...data, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); await updateDoc(ref, { id: ref.id }); await incrementUserStats(uid, 'pulseCount', 1); return { ...data, id: ref.id, createdAt: new Date(), updatedAt: new Date() }; }
export async function getPulse(id: string): Promise<Pulse | null> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); const snap = await getDoc(doc(clients.db, 'pulses', id)); return snap.exists() ? (snap.data() as Pulse) : null; }
export async function listUserPulses(uid: string, max = 20): Promise<Pulse[]> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); const q = query(collection(clients.db, 'pulses'), where('uid','==',uid), orderBy('createdAt','desc'), limit(max)); const snap = await getDocs(q); return snap.docs.map((d) => d.data() as Pulse); }
export async function findCandidatePulses(input: Pick<Pulse, 'dateKey'|'visibility'|'mood'|'timeSlot'|'placeCategory'>, max = 40): Promise<Pulse[]> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); const queries = [ query(collection(clients.db, 'pulses'), where('dateKey','==',input.dateKey), where('visibility','==','anonymousPublic'), where('mood','==',input.mood), limit(max)), query(collection(clients.db, 'pulses'), where('dateKey','==',input.dateKey), where('visibility','==','anonymousPublic'), where('timeSlot','==',input.timeSlot), limit(max)), query(collection(clients.db, 'pulses'), where('dateKey','==',input.dateKey), where('visibility','==','anonymousPublic'), where('placeCategory','==',input.placeCategory), limit(max)) ]; const snaps = await Promise.all(queries.map((q) => getDocs(q))); const map = new Map<string, Pulse>(); snaps.flatMap((s) => s.docs).forEach((d) => map.set(d.id, d.data() as Pulse)); return Array.from(map.values()).slice(0, max); }
export async function makePulsePrivate(id: string): Promise<void> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); await updateDoc(doc(clients.db, 'pulses', id), { visibility: 'private', updatedAt: serverTimestamp() }); }
export async function updatePulseWord(id: string, word: string): Promise<void> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); await updateDoc(doc(clients.db, 'pulses', id), { word, updatedAt: serverTimestamp() }); }
export async function deletePulse(id: string): Promise<void> { const clients = getFirebaseClients(); if (!clients) throw new Error('Firebase is not configured.'); await deleteDoc(doc(clients.db, 'pulses', id)); }
